export interface Client {
  id: string;
  name: string;
  phone: string;
  email?: string;
  notes?: string;
  createdAt: number;
}

export enum PaymentStatus {
  PENDING = 'Pendente',
  PARTIAL = 'Parcial',
  PAID = 'Pago',
}

export interface Appointment {
  id: string;
  clientId: string;
  service: string;
  date: string; // ISO Date string YYYY-MM-DD
  time: string; // HH:mm
  duration: number; // minutes
  price: number;
  deposit: number; // Sinal
  status: PaymentStatus;
  procedureNotes?: string; // Notes about what was done
  aiSummary?: string; // Generated by Gemini
}

export interface DailyStats {
  totalAppointments: number;
  expectedIncome: number;
  receivedIncome: number;
}